import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Toggle from "../components/Toggle.js";
import FadeUp from "../animations/FadeUp";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen w-full flex flex-col items-center justify-center  bg-white dark:bg-neutral-900">
        <FadeUp>
          <h1 className="text-3xl font-bold text-blue-500 dark:text-red-500">
            Hello world!
          </h1>
        </FadeUp>
        <Toggle />
      </main>
    </div>
  );
}
