import Head from "next/head";
import Image from "next/image";
import Toggle from "../components/Toggle.js";
import FadeUp from "../animations/FadeUp";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen w-full flex flex-col justify-center items-center p-12  bg-white dark:bg-neutral-900">
        {/* Place the toggle switch wherever you'd like */}
        <Toggle />
        {/* Wrap your JSX Element in a motion component (animations) */}
        <FadeUp>
          <h1 className="text-3xl font-bold text-neutral-900 dark:text-neutral-100">
            Nextjs 13 with TailwindCSS, Framer-Motion, and Theme Toggle
          </h1>
        </FadeUp>
      </main>
    </>
  );
}

